"""Add marketing consent to clients

Revision ID: 0815f8c795bf
Revises: 6c80d6b619d3
Create Date: 2026-02-27 13:20:35.773962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0815f8c795bf'
down_revision = '6c80d6b619d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketing_consent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('marketing_consented_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('marketing_consented_at')
        batch_op.drop_column('marketing_consent')

    # ### end Alembic commands ###
