"""Add image_filename, best_for, pressure_level to services

Revision ID: 6c80d6b619d3
Revises: e751a564979e
Create Date: 2026-02-27 11:11:35.813401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c80d6b619d3'
down_revision = 'e751a564979e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('best_for', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pressure_level', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('pressure_level')
        batch_op.drop_column('best_for')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
