"""add unique constraint on reminder_log booking_id status

Revision ID: bae643dbf04a
Revises: 0815f8c795bf
Create Date: 2026-02-28 13:48:51.894950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae643dbf04a'
down_revision = '0815f8c795bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reminder_booking_sent', ['booking_id', 'status'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reminder_booking_sent', type_='unique')

    # ### end Alembic commands ###
